### ISSUE TITLE
How to enable NVMe drivers in this board? 

### ISSUE THREAD

**Issue by msharmavikram** [open-power/capiflash#24]
Hi there, 
I am using this system with 2 boards. I configured it to have a legacy mode and I see the devices getting configured as regular block sd* devices. How do I enable NVMe drivers for these SSDs/ 

Machine: IBM Minsky platform. 
OS: Ubuntu 16.04

**Comment by vageline** [comment]
I assume you have "FlashGT" cards, where each card has two M.2 NVMe sticks. Our capiflash software uses the scsi stack. An NVMe driver is not available.
To use in legacy mode, mkfs to a /dev/sd* device listed with cxlfstatus and mount the fs.
We also have a "superpipe" block r/w interface which bypasses the kernel:
   cblk_open(/dev/sg*), cblk_read(),cblk_write(),cblk_close()

**Comment by msharmavikram** [comment]
Thanks @vageline 
I was able to do the things you mentioned. Given that M.2 are NVMe compatible, I was wondering if there is a method to use NVMe.

**Comment by vageline** [comment]
for the best performance with legacy, use multi-queue with 40 queues
