### ISSUE TITLE
spec: Comments about API doc

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/capiflash#3]
https://github.com/open-power/capiflash/blob/master/src/block/README.md

Behind the flag constants there seem some spaces to me missing.

**Comment by fhaverkamp** [comment]
int rc = cblk_get_lun_size(chunk_id_t chunk_id, size_t *size, int flags))

I think there the )) are one too many. Watch out, this is duplicated multiple times.

**Comment by fhaverkamp** [comment]
offset_t lba; /\* Starting Logical block address for */

I think this is not a standard data type. Is that off_t or off64_t? Maybe describe this.

**Comment by fhaverkamp** [comment]
The 4KiB is a given or? I mean over time maybe alternate block sizes might make some sense?
So size is not actually the size but something like no_of_4kib_blocks, isn't it?

**Comment by fhaverkamp** [comment]
Return values and errno. Mostly you just say not 0 is error, but no distinguishing how to interpret the non zero values. Same with errno. Any effort to make this more precise?

**Comment by williamspatrick** [comment]
@fhaverkamp - Some of your suggestions are pretty minor changes to the 'docs'.  The team might appreciate if you give them a pull request with your proposal.

**Comment by fhaverkamp** [comment]
https://github.com/open-power/capiflash/pulls

@williamspatrick Here it is. Now it is up to you to review and integrate quickly to get your new contributor happy ;-).

**Comment by williamspatrick** [comment]
@fhaverkamp - Thank you.  I'm actually not the maintainer of this code.  I'll assign the pull request to them though.

**Comment by vageline** [comment]
the pull request was merged
