### ISSUE TITLE
Error building on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [open-power/capiflash#9]
Hi All,

I am trying to build capiflash on Ubuntu 16.04 ppc64le as per the steps in the readme https://github.com/open-power/capiflash#ibm-data-engine-for-nosql-software-libraries

I get the following error when running make -j32. The previous worked correctly, any pointers or help would be highly appreciated, thanks!

root@030a5adc15f5:/capiflash# make -j32
make dep
make[1]: Entering directory '/capiflash'
cd src && make dep
WARNING: Downloading new cxlflash_ioctl.h from Jenkins
mkdir -p ./src/include/scsi
make[2]: Entering directory '/capiflash/src'
wget -P ./src/include/scsi -q http://hydepark.aus.stglabs.ibm.com:8081/job/ga2-kernel/lastSuccessfulBuild/artifact/linux/include/uapi/scsi/cxlflash_ioctl.h
config.linux.mk:331: recipe for target 'src/include/scsi/cxlflash_ioctl.h' failed
make[1]: *** [src/include/scsi/cxlflash_ioctl.h] Error 4
make[1]: *** Waiting for unfinished jobs....
cd lib && make dep
make[3]: Entering directory '/capiflash/src/lib'
cd arkalloc && make dep
WARNING: Downloading new cxlflash_ioctl.h from Jenkins
mkdir -p ../../src/include/scsi
make[4]: Entering directory '/capiflash/src/lib/arkalloc'
wget -P ../../src/include/scsi -q http://hydepark.aus.stglabs.ibm.com:8081/job/ga2-kernel/lastSuccessfulBuild/artifact/linux/include/uapi/scsi/cxlflash_ioctl.h
../../config.linux.mk:331: recipe for target '../../src/include/scsi/cxlflash_ioctl.h' failed
make[3]: *** [../../src/include/scsi/cxlflash_ioctl.h] Error 4
make[3]: *** Waiting for unfinished jobs....
/bin/gcc  -M  -fPIC -O3 -Wall -mcpu=power8 -mtune=power8 -DGITREVISION='"6-6e1a255"' -DGITREVISION='"6-6e1a255"' -DGITREVISION='"6-6e1a255"' -DGITREVISION='"6-6e1a255"' -D__SURELOCK_MODULE=arkalloc -DGITREVISION='"6-6e1a255"'  -DTARGET_ARCH_PPC64EL -R '$ADV_TOOLCHAIN_PATH/lib64:$ORIGIN/../lib:$ORIGIN:/lib:/usr/lib:/opt/ibm/capikv/lib' -I../../../src/include/ -I../../../obj/genfiles -I/capiflash/src/lib/arkalloc -Werror zmalloc.c -o ../../../obj/modules/arkalloc/zmalloc.dep.$$ -I../../../src/include/ -I../../../obj/genfiles -I/capiflash/src/lib/arkalloc -iquote .; \
sed 's,\(zmalloc\)\.o[ :]*,../../../obj/modules/arkalloc/\1.o ../../../obj/modules/arkalloc/zmalloc.dep : ,g' < ../../../obj/modules/arkalloc/zmalloc.dep.$$ > ../../../obj/modules/arkalloc/zmalloc.dep;
/bin/bash: /bin/gcc: No such file or directory
/bin/bash: line 1: ../../../obj/modules/arkalloc/zmalloc.dep.6710: No such file or directory
make[4]: *** No rule to make target '../../../obj/modules/arkalloc/zmalloc.dep', needed by 'dep'.  Stop.
make[4]: Leaving directory '/capiflash/src/lib/arkalloc'
../../config.linux.mk:275: recipe for target 'arkalloc.dep' failed
make[3]: *** [arkalloc.dep] Error 2
make[3]: Leaving directory '/capiflash/src/lib'
../config.linux.mk:275: recipe for target 'lib.dep' failed
make[2]: *** [lib.dep] Error 2
make[2]: Leaving directory '/capiflash/src'
config.linux.mk:275: recipe for target 'src.dep' failed
make[1]: *** [src.dep] Error 2
make[1]: Leaving directory '/capiflash'
config.linux.mk:29: recipe for target 'ship' failed
make: *** [ship] Error 2

**Comment by vageline** [comment]
This should be fixed. Pull and retry.
